version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp_development

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/myapp_development
      RAILS_ENV: development
    volumes:
      - .:/rails
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

volumes:
  postgres_data:
