default: &default
  adapter: postgresql
  encoding: unicode
  database: anime_listing
  username: postgres
  password: root
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: anime_listing_development

test:
  <<: *default
  database: anime_listing_test

production:
  <<: *default
  database: anime_listing_production
  username: anime_listing
  password: <%= ENV["ANIME_LISTING_DATABASE_PASSWORD"] %>
